sonar.projectKey=connectbot_connectbot
sonar.organization=connectbot
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.source=17
sonar.kotlin.source=17

sonar.coverage.jacoco.xmlReportPaths=\
  app/build/reports/coverage/test/oss/debug/report.xml,\
  app/build/reports/coverage/test/google/debug/report.xml,\
  app/build/reports/coverage/androidTest/oss/debug/report.xml,\
  app/build/reports/coverage/androidTest/google/debug/report.xml

sonar.java.binaries=app/build/intermediates/javac/ossDebug/compileOssDebugJavaWithJavac/classes,\
  app/build/intermediates/javac/googleDebug/compileGoogleDebugJavaWithJavac/classes

sonar.java.libraries=app/build/intermediates/aar_libs_directory/ossDebug/collectOssDebugLibs/jars
