sonar.projectKey=connectbot_connectbot
sonar.organization=connectbot
sonar.host.url=https://sonarcloud.io

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.source=17
sonar.coverage.jacoco.xmlReportPaths=\
  app/build/reports/kover/reportOssDebug.xml,\
  app/build/reports/kover/reportGoogleDebug.xml,\
  app/build/reports/coverage/androidTest/oss/debug/report.xml,\
  app/build/reports/coverage/androidTest/google/debug/report.xml

sonar.java.binaries=app/build/intermediates/classes/ossDebug/jacocoOssDebug/dirs,\
  app/build/intermediates/javac/ossDebug/compileOssDebugJavaWithJavac/classes,\
  app/build/intermediates/javac/googleDebug/compileGoogleDebugJavaWithJavac/classes

sonar.java.test.binaries=app/build/intermediates/classes/ossDebugUnitTest/transformOssDebugUnitTestClassesWithAsm/dirs,\
  app/build/intermediates/classes/googleDebugUnitTest/transformGoogleDebugUnitTestClassesWithAsm/dirs,\
  app/build/intermediates/javac/ossDebugAndroidTest/compileOssDebugAndroidTestJavaWithJavac/classes,\
  app/build/intermediates/javac/googleDebugAndroidTest/compileGoogleDebugAndroidTestJavaWithJavac/classes
