name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this is related to a UI problem or otherwise applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: connectbot-version
    attributes:
      label: ConnectBot version
      description: You can find this in the app under Menu > Help > About.
      placeholder: "1.9.10"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Android device
      placeholder: "Google Pixel 8"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: "Android 14"
    validations:
      required: true

  - type: dropdown
    id: install-source
    attributes:
      label: Installed from
      options:
        - Google Play
        - F-Droid
        - GitHub releases
        - Built from source
        - Other
    validations:
      required: true

  - type: input
    id: server-os
    attributes:
      label: Server OS
      description: If applicable, what operating system is the server running?
      placeholder: "Ubuntu 24.04"
    validations:
      required: false

  - type: input
    id: ssh-version
    attributes:
      label: SSH software and version
      description: If applicable, what SSH server software and version?
      placeholder: "OpenSSH 9.6"
    validations:
      required: false

  - type: input
    id: key-type
    attributes:
      label: Key type used
      description: If applicable, what type of SSH key are you using?
      placeholder: "Ed25519, RSA 4096-bit"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
