name: Feature request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your needs.

  - type: input
    id: connectbot-version
    attributes:
      label: ConnectBot version
      description: You can find this in the app under Menu > Help > About.
      placeholder: "1.9.10"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: "Android 14"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
