/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.connectbot;

public final class R {
    public static final class anim {
        public static final int fade_out=0x7f040000;
        public static final int fade_stay_hidden=0x7f040001;
        public static final int slide_left_in=0x7f040002;
        public static final int slide_left_out=0x7f040003;
        public static final int slide_right_in=0x7f040004;
        public static final int slide_right_out=0x7f040005;
    }
    public static final class array {
        public static final int list_colors=0x7f060001;
        public static final int list_emulation_modes=0x7f060000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int blue=0x7f080000;
        public static final int green=0x7f080001;
        public static final int red=0x7f080002;
    }
    public static final class drawable {
        public static final int blue=0x7f020005;
        public static final int connected=0x7f020000;
        public static final int even_stripe=0x7f020006;
        public static final int highlight_disabled_pressed=0x7f020001;
        public static final int ic_btn_back=0x7f020002;
        public static final int ic_btn_next=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int odd_stripe=0x7f020007;
    }
    public static final class id {
        public static final int action_next=0x7f090005;
        public static final int action_prev=0x7f090004;
        public static final int console_flip=0x7f090000;
        public static final int front_quickconnect=0x7f090001;
        public static final int terminal_overlay=0x7f090006;
        public static final int wizard_flipper=0x7f090003;
        public static final int wizard_scroll=0x7f090002;
    }
    public static final class layout {
        public static final int act_console=0x7f030000;
        public static final int act_hostlist=0x7f030001;
        public static final int act_wizard=0x7f030002;
        public static final int item_host=0x7f030003;
        public static final int item_terminal=0x7f030004;
        public static final int wiz_eula=0x7f030005;
        public static final int wiz_features=0x7f030006;
    }
    public static final class string {
        public static final int alert_disconnect_msg=0x7f070015;
        public static final int app_desc=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int bind_days=0x7f07001a;
        public static final int bind_hours=0x7f070019;
        public static final int bind_minutes=0x7f070018;
        public static final int button_add=0x7f070011;
        public static final int button_cancel=0x7f070012;
        public static final int button_change=0x7f070013;
        public static final int button_generate=0x7f070014;
        public static final int button_ok=0x7f070010;
        public static final int menu_about=0x7f07000e;
        public static final int menu_delete=0x7f07000b;
        public static final int menu_insert=0x7f07000a;
        public static final int menu_preferences=0x7f07000c;
        public static final int menu_pubkey=0x7f07000d;
        public static final int msg_copyright=0x7f070016;
        public static final int msg_version=0x7f070017;
        public static final int prompt_touch=0x7f07000f;
        public static final int resolve_connect=0x7f070009;
        public static final int resolve_edit=0x7f070008;
        public static final int title_entropy=0x7f070007;
        public static final int title_host=0x7f070003;
        public static final int title_hosts_list=0x7f070002;
        public static final int title_password=0x7f070005;
        public static final int title_pubkey=0x7f070006;
        public static final int title_shell=0x7f070004;
    }
    public static final class xml {
        public static final int host_prefs=0x7f050000;
        public static final int preferences=0x7f050001;
    }
}
