/*
 * ConnectBot: simple, powerful, open-source SSH client for Android
 * Copyright 2026 Kenny Root
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.connectbot.transport

import com.trilead.ssh2.Connection
import com.trilead.ssh2.ExtensionInfo
import com.trilead.ssh2.packets.PacketExtInfo
import com.trilead.ssh2.transport.TransportManager
import timber.log.Timber

/**
 * Prevents Android Keystore RSA keys from falling back to an unsupported SHA-1 signature.
 *
 * sshlib chooses `ssh-rsa` when a server omits the optional `server-sig-algs` extension. Modern
 * servers still support RSA SHA-2 in this situation, but Android Keystore keys generated by
 * ConnectBot intentionally do not authorize SHA-1. Until sshlib exposes a public preference API,
 * update its negotiated extension state before public-key authentication.
 */
internal object RsaSignatureAlgorithmPolicy {
    val rsaSha2Algorithms = listOf("rsa-sha2-512", "rsa-sha2-256")

    fun prepareForAuthentication(connection: Connection): Boolean = try {
        val transportManager = getTransportManager(connection) ?: return false
        val acceptedAlgorithms = transportManager.extensionInfo.signatureAlgorithmsAccepted

        when {
            acceptedAlgorithms.any(rsaSha2Algorithms::contains) -> true
            acceptedAlgorithms.isNotEmpty() -> false
            else -> preferRsaSha2(transportManager)
        }
    } catch (e: ReflectiveOperationException) {
        Timber.w(e, "Unable to prepare RSA SHA-2 public-key authentication")
        false
    } catch (e: SecurityException) {
        Timber.w(e, "Unable to prepare RSA SHA-2 public-key authentication")
        false
    }

    private fun getTransportManager(connection: Connection): TransportManager? = Connection::class.java.getDeclaredField(CONNECTION_TRANSPORT_MANAGER_FIELD).run {
        isAccessible = true
        get(connection) as? TransportManager
    }

    private fun preferRsaSha2(transportManager: TransportManager): Boolean {
        val extensionInfo = ExtensionInfo.fromPacketExtInfo(
            PacketExtInfo(mapOf(SERVER_SIGNATURE_ALGORITHMS to rsaSha2Algorithms.joinToString(","))),
        )
        TransportManager::class.java.getDeclaredField(TRANSPORT_EXTENSION_INFO_FIELD).run {
            isAccessible = true
            set(transportManager, extensionInfo)
        }
        return true
    }

    private const val CONNECTION_TRANSPORT_MANAGER_FIELD = "tm"
    private const val TRANSPORT_EXTENSION_INFO_FIELD = "extensionInfo"
    private const val SERVER_SIGNATURE_ALGORITHMS = "server-sig-algs"
}
