/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_ase_Exec */

#ifndef _Included_com_google_ase_Exec
#define _Included_com_google_ase_Exec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_ase_Exec
 * Method:    createSubprocess
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_google_ase_Exec_createSubprocess
  (JNIEnv *, jclass, jstring, jstring, jstring, jintArray);

/*
 * Class:     com_google_ase_Exec
 * Method:    setPtyWindowSize
 * Signature: (Ljava/io/FileDescriptor;IIII)V
 */
JNIEXPORT void JNICALL Java_com_google_ase_Exec_setPtyWindowSize
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_google_ase_Exec
 * Method:    waitFor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_google_ase_Exec_waitFor
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_ase_Exec
 * Method:    register
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_ase_Exec_register
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
