name: Lint documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '.java-version'
      - 'icons/**'
  workflow_call:
    secrets:
      GRADLE_CACHE_ENCRYPTION_KEY:
        required: false

jobs:
  lint:
    name: Lint docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          cache-read-only: true

      - name: Delete old Android SDK cmdline-tools
        run: |
          rm -rf "$ANDROID_HOME/cmdline-tools/latest"

      - name: Setup Android SDK
        uses: android-actions/setup-android@be39fa834029ff78f1a44aa3bb0819b8fc2bd8fd # v4.0.4
        with:
          packages: 'cmdline-tools;latest platform-tools'

      - name: Check formatting
        run: ./gradlew spotlessCheck
