name: Lint documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '.java-version'
      - 'icons/**'
  workflow_call:
    secrets:
      GRADLE_CACHE_ENCRYPTION_KEY:
        required: false

jobs:
  lint:
    name: Lint docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Set up JDK
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          cache-read-only: true

      - name: Delete old Android SDK cmdline-tools
        run: |
          rm -rf "$ANDROID_HOME/cmdline-tools/latest"

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
        with:
          cmdline-tools-version: '13114758'
          packages: 'cmdline-tools;latest tools platform-tools'

      - name: Check formatting
        run: ./gradlew spotlessCheck
