name: Lint documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '.java-version'
      - 'icons/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
      - 'LICENSE'
      - '.java-version'
      - 'icons/**'

jobs:
  lint:
    name: Lint docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
          cache-read-only: true

      - name: Delete old Android SDK cmdline-tools
        run: |
          rm -rf $ANDROID_HOME/cmdline-tools/latest

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
        with:
          cmdline-tools-version: '13114758'
          packages: 'cmdline-tools;latest tools platform-tools'

      - name: Check formatting
        run: ./gradlew spotlessCheck
