/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.theb.ssh;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020001;
        public static final int even_stripe=0x7f020002;
        public static final int icon=0x7f020000;
        public static final int odd_stripe=0x7f020003;
    }
    public static final class id {
        public static final int add=0x7f050006;
        public static final int cancel=0x7f050007;
        public static final int dismiss=0x7f05000a;
        public static final int hostname=0x7f050003;
        public static final int hostnameLabel=0x7f050002;
        public static final int message=0x7f050009;
        public static final int ok=0x7f05000d;
        public static final int output=0x7f05000e;
        public static final int password=0x7f05000c;
        public static final int passwordLabel=0x7f05000b;
        public static final int port=0x7f050005;
        public static final int portLabel=0x7f050004;
        public static final int shell=0x7f050008;
        public static final int username=0x7f050001;
        public static final int usernameLabel=0x7f050000;
    }
    public static final class layout {
        public static final int host_editor=0x7f030000;
        public static final int main=0x7f030001;
        public static final int message_dialog=0x7f030002;
        public static final int password_dialog=0x7f030003;
        public static final int secure_shell=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int button_add=0x7f040009;
        public static final int button_cancel=0x7f04000a;
        public static final int button_change=0x7f04000b;
        public static final int button_ok=0x7f040008;
        public static final int menu_delete=0x7f040007;
        public static final int menu_insert=0x7f040006;
        public static final int resolve_edit=0x7f040005;
        public static final int title_host=0x7f040002;
        public static final int title_hosts_list=0x7f040001;
        public static final int title_password=0x7f040004;
        public static final int title_shell=0x7f040003;
    }
}
